binanceus:
  file_pattern: "binanceus_transaction_history.csv"
  mapping:
    timestamp: "Time"
    type: "Category"
    asset: "Primary Asset"
    quantity: "Realized Amount For Primary Asset"
    price: "Realized Amount for Primary Asset in USD"
    fees: "Realized Amount for Fee Asset in USD"
    currency: "Quote Asset"
    source_account: "Withdraw Method"
    destination_account: "Payment Method"
    account_owner: "nash"

coinbase:
  file_pattern: "coinbase_transaction_history.csv"
  mapping:
    timestamp: "Timestamp"
    type: "Transaction Type"
    asset: "Asset"
    quantity: "Quantity Transacted"
    price: "Price at Transaction"
    fees: "Fees and/or Spread"
    currency: "Price Currency"
    source_account: ""
    destination_account: ""
    account_owner: "nash"

gemini:
  staking:
    file_pattern: "gemini_staking_transaction_history.csv"
    mapping:
      timestamp: "Date"  # Optionally combine with "Time (UTC)"
      type: "Type"
      asset: "Symbol"
      quantity: "Amount USD"
      price: "Price USD"
      fees: ""
      currency: "USD"
      source_account: ""
      destination_account: ""
      account_owner: "nash"

  transactions:
    file_pattern: "gemini_transaction_history.csv"
    mapping:
      timestamp: "Date"  # Optionally combine with "Time (UTC)"
      type: "Type"
      asset: "Symbol"
      quantity: "USD Amount USD"
      price: ""  # Derivable, if needed
      fees: "Fee (USD) USD"
      currency: "USD"
      source_account: "Withdrawal Destination"
      destination_account: "Deposit Destination"
      account_owner: "nash"
